baseURL = 'https://georgepaps.pages.dev'
languageCode = 'en-us'
title = 'George Paps Blog'
theme = 'stack-theme' 
math = true

[params]
favicon = "/favicon.ico"

[Params.sidebar]

subtitle = 'Thoughts on machine learning, books, politics, and finance. Feel free to reach me in georgezpaps@protonmail.com'

[Params.sidebar.avatar]

local = false
src = '/img/Cézanne -Mont Sainte-Victoire.jpg'

#[widgets]
#[[widgets.homepage]]
#type = 'search'
#[[widgets.homepage]]
#type = 'archives'
#params.limit = 5
#[[widgets.homepage]]
#type = 'categories'
#params.limit = 10
#[[widgets.homepage]]
#type = 'tag-cloud'
#params.limit = 10

[menu]
main = []

[[menu.social]]

identifier = 'github'
name = 'GitHub'
url = 'https://github.com/GeorgePaps'
params.icon = 'brand-github'    
