baseURL = 'https://georgepaps.pages.dev'
languageCode = 'en-us'
title = 'George Paps Blog'
theme = 'stack-theme' 
math = true

[params]
favicon = "/favicon.ico"

[Params.sidebar.avatar]

local = false
src = '/img/engin-akyurt-Hlkuojv_P6I-unsplash.jpg'
